name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set version number
      run: |
        echo "GIT_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build -t "${{secrets.IMAGE_NAME}}":latest -t ${{ secrets.IMAGE_NAME }}:${GIT_COMMIT_SHA} .
    - name: push image to docker hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push "${{secrets.IMAGE_NAME}}":latest
        docker push ${{ secrets.IMAGE_NAME }}:${GIT_COMMIT_SHA}
